### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Bharathumb** [BayoDev/Twitch-Best-Of-Gen#11]
Traceback (most recent call last):
  File "F:\compli\Twitch-Best-Of-Gen-main\Twitch-Best-Of-Gen-main\main.py", line 5, in <module>
    from modules.input_handler import *
  File "F:\compli\Twitch-Best-Of-Gen-main\Twitch-Best-Of-Gen-main\modules\input_handler.py", line 4, in <module>
    from cv2 import fastNlMeansDenoising
ModuleNotFoundError: No module named 'cv2

**Comment by BayoDev** [comment]
I fixed it. Download it again and it should work
