### ISSUE TITLE
Please troubleshoot this if possible 

### ISSUE THREAD

**Issue by Bharathumb** [BayoDev/Twitch-Best-Of-Gen#12]
Checking if the category is available...
Traceback (most recent call last):
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\service.py", line 72, in start
    self.process = subprocess.Popen(cmd, env=self.env,
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:\compli\Twitch-Best-Of-Gen-main\main.py", line 72, in <module>
    main()
  File "F:\compli\Twitch-Best-Of-Gen-main\main.py", line 37, in main
    name,nclips,range,iPath,type,langs = getInputs()
  File "F:\compli\Twitch-Best-Of-Gen-main\modules\input_handler.py", line 124, in getInputs
    resp = isCategory(ca)
  File "F:\compli\Twitch-Best-Of-Gen-main\modules\twitchClips.py", line 38, in isCategory
    data = getLoadedPageContent("https://www.twitch.tv/directory/game/"+name,delay=15)
  File "F:\compli\Twitch-Best-Of-Gen-main\modules\twitchClips.py", line 56, in getLoadedPageContent
    driver = webdriver.Chrome(options=options)
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 73, in __init__
    self.service.start()
  File "C:\Users\ADMIN\AppData\Local\Programs\Python\Python310\lib\site-packages\selenium\webdriver\common\service.py", line 81, in start
    raise WebDriverException(
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home

**Comment by BayoDev** [comment]
Do you have the webdrivers installed and added to PATH?
If you don't follow the instructions [here](https://www.selenium.dev/documentation/webdriver/getting_started/install_drivers/)
