### ISSUE TITLE
:/

### ISSUE THREAD

**Issue by NimaWoods** [BayoDev/Twitch-Best-Of-Gen#18]
[i]Fetching data
Traceback (most recent call last):
  File "C:\Users\nikla\Desktop\Twitch-Best-Of-0.0.1\main.py", line 93, in <module>
    main()
  File "C:\Users\nikla\Desktop\Twitch-Best-Of-0.0.1\main.py", line 54, in main
    data = fetch_clips_channel(name,max=nclips,range=range_in)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikla\Desktop\Twitch-Best-Of-0.0.1\modules\twitchClips.py", line 132, in fetch_clips_channel
    data = bs(get_loaded_page_content(f"https://www.twitch.tv/{channel_name}/clips?filter=clips&range={range}",type='channel'),'html.parser')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikla\Desktop\Twitch-Best-Of-0.0.1\modules\twitchClips.py", line 64, in get_loaded_page_content
    WebDriverWait(driver,60).until(lambda test : len(driver.find_elements_by_tag_name('article'))!=0)
  File "C:\Users\nikla\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 86, in until
    value = method(self._driver)
            ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nikla\Desktop\Twitch-Best-Of-0.0.1\modules\twitchClips.py", line 64, in <lambda>
    WebDriverWait(driver,60).until(lambda test : len(driver.find_elements_by_tag_name('article'))!=0)
                                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'WebDriver' object has no attribute 'find_elements_by_tag_name'

**Comment by BayoDev** [comment]
Try running pip install --upgrade -r requirements.txt

**Comment by BayoDev** [comment]
Update me on the outcome
